# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d6491820cca37b32ed09dadd17052f1534f3a14b9577307b6ac66181c93d482b16108dfb76495ed0f159c2c8651b2a236d7c112e7d04a27683b07f9b03eead6

test:
  secret_key_base: afe861baad5e800ed9f36e7592f5a21e71933f04678330f2695661cfa6da65976a54942a54a367a9a7eb9552bec9a50870a367715035183ca1885f3f394a8a25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
